version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile.base
        tty: true
        command: sh -c "cargo prisma generate && cargo test"
        volumes:
            - .:/usr/src/app
            - .cache/cargo-cache:/usr/local/cargo/target
        env_file:
            - .env
