FROM rust:1.78 as build

WORKDIR /backend

RUN apt-get update && apt-get install -y \
	libssl-dev \
	pkg-config \
	libpq-dev \
	&& rm -rf /var/lib/apt/lists/*

COPY . .
COPY .cargo .

RUN cargo prisma generate
RUN cargo build --release

FROM rust:1.78-slim-buster

COPY --from=build /backend/target/release/backend .

CMD ["./backend"]