services:
    postgres:
        extends:
            file: docker-compose-db.yml
            service: postgres

    redis:
        extends:
            file: docker-compose-db.yml
            service: redis

    app:
        build:
            context: .
            dockerfile: Dockerfile.dev
        tty: true
        command: sh -c "cargo prisma generate && cargo prisma db push && cargo run --release"
        volumes:
            - .:/usr/src/app
            - .cache/cargo-cache:/usr/local/cargo/target
        depends_on:
            postgres:
                condition: service_healthy
            redis:
                condition: service_healthy
        ports:
            - '3000:3000'
        environment:
            RUST_LOG: error
            DATABASE_URL: postgresql://postgres:postgres@postgres:5432/postgres?schema=public
            REDIS_URL: redis://redis:6379
