version: '3.8'

services:
    postgres:
        image: postgres:latest
        tty: true
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        ports:
            - '5432:5432'
        volumes:
            - '.cache/postgres:/var/lib/postgresql/data'
