apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: backend
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: app-env
        volumeMounts:
        - mountPath: /usr/src/app
          name: app-volume
      volumes:
      - name: app-volume
        persistentVolumeClaim:
          claimName: app-pvc
