apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: backend/app-image
        command: ["sh", "-c", "cargo prisma generate && cargo run"]
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: app-env
        volumeMounts:
        - mountPath: /usr/src/app
          name: app-volume
      volumes:
      - name: app-volume
        persistentVolumeClaim:
          claimName: app-pvc