services:
    dashboard:
        build:
            context: .
            dockerfile: Dockerfile.base
        command: sh -c "npm install && npm run start"
        tty: true
        volumes:
            - .:/usr/src/app
        ports:
            - '8081:8081'
        environment:
            NODE_ENV: development
