version: '3.8'

services:
  metabase:
    image: metabase/metabase
    container_name: metabase
    ports:
      - "3000:3000"
    volumes:
      - /metabase/metabase.db:/metabase.db
    restart: unless-stopped