services:
    app:
        build:
            context: .
            dockerfile: Dockerfile.base
        volumes:
            - .:/app
        env_file:
            - .env
        command: python src/main.py
