services:
    docs:
        build:
            context: .
            dockerfile: Dockerfile.base
        command: sh -c "bun install && bun dev"
        tty: true
        volumes:
            - .:/usr/src/app
        ports:
            - '4321:4321'
        environment:
            NODE_ENV: development
