name: LoadTest API
on:
    push:
        branches: ['main']
        paths:
            - 'src/backend/**'
            - 'src/load_test/**'

jobs:
    load_tests:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup API service
              uses: hoverkraft-tech/compose-action@v2.0.0
              with:
                compose-file: "./src/backend/docker-compose-actions.yml"
                services: |
                    postgres
                    redis
                    app

            - name: Setup Node
              uses: actions/setup-node@v4

            - name: Install dependencies and bundle
              run: |
                cd src/load_test
                npm install
                npm run bundle

            - name: Wait for API to be ready
              run: |
                retries=0
                until curl -s -o /dev/null -w "%{http_code}" http://localhost:3000/ | grep -q 200; do
                retries=$((retries+1))
                if [ $retries -gt 100 ]; then
                    echo "API not ready after 5 retries, exiting..."
                    exit 1
                fi
                echo "API not ready, retrying in 5 seconds..."
                sleep 5
                done
                echo "API is ready!"

            - name: Run local k6 test
              uses: grafana/k6-action@v0.3.1
              with:
                  filename: ./src/load_test/dist/main.test.js
                  flags: --out json=summary.json
              env:
                  HOSTNAME: 'localhost'

            - name: Upload k6 results
              uses: actions/upload-artifact@v4
              with:
                  name: k6-results
                  path: summary.json
